### ISSUE TITLE
Set up to open this project in a development container

### ISSUE THREAD

**Issue by kim-take** [kim-take/ifc-js-sample-app#1]
### ToDos
- [x] Install [Remote Development extension pack](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack) to VS Code (ms-vscode-remote.vscode-remote-extensionpack)
- [x] Install Docker Desktop
- [x] Open this repo*  in VS Code
- [x] Generate .devcontainer
- [x] Push it to this repo
- [x] Open it on another machine
- [ ] Next try is to open a locally cloned repo in a container

*Open this repo:
run Remote-Containers: Clone Repository in Container Volume... from the Command Palette

To Run:
1. Open integrated terminal.
2. Enter the commands.
    - yarn install
    - yarn setup
    - yarn dev

### Reference:
- [Visual Studio Code: Remote Development with Containers & Codespaces | Remote Development Part 1](https://docs.microsoft.com/en-us/shows/tabs-vs-spaces/visual-studio-code-remote-dev-with-containers--codespaces)
- [Remote development in Containers](https://code.visualstudio.com/docs/remote/containers-tutorial)
- [Developing inside a Container](https://code.visualstudio.com/docs/remote/containers)
- [Open a Git repository or GitHub PR in an isolated container volume](https://code.visualstudio.com/docs/remote/containers#_quick-start-open-a-git-repository-or-github-pr-in-an-isolated-container-volume)

**Comment by kim-take** [comment]
Generate .devcontainer
85ba681c5d71c086ecfc50f2c469b36d5c2e0bb5
